language: node_js

node_js:
  - "8"

env:
  global:
    - GH_REF: github.com/bem/html-differ.git
    - ISTANBUL_COVERAGE: true

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
